# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Deploy
        deployment: production
        caches:
          - node
        script: 
        - pipe: atlassian/ftp-deploy:0.2.1
          variables:
            USER: $FTP_USERNAME
            PASSWORD: $FTP_PASSWORD
            SERVER: 'ftp://aaronjenkins.me'
            REMOTE_PATH: 'public_html/reviews'
            LOCAL_PATH: '/docs'
            EXTRA_ARGS: '-P 21'
